### ISSUE TITLE
signup/logIn画面のUIに統一性を持たせる

### ISSUE THREAD

**Issue by tam-t-3** [Takashi-Tamura/Graph-App-Prd#37]
TextFieldのMaterial-UIのデザインを修正

**Comment by Takashi-Tamura** [comment]
SignIn.tsxにTextFieldborderを追加し
【未完了タスク】
・placeholderの位置修正

**Comment by Takashi-Tamura** [comment]
SignIn.tsxにTextFieldborderを追加
【完了タスク】
・placeholderの位置修正済み
【未完了タスク】
・リファクタリング & ブランチエラー修正

**Comment by Takashi-Tamura** [comment]
【未完了タスク】
ブランチエラー
とFooterデザインを修正
